services:
  planner:
    image: lobanovsky/planner:${TAG}
    container_name: planner
    restart: always
    environment:
      TZ: Europe/Moscow
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BOT_WEBHOOK_URL: ${BOT_WEBHOOK_URL}
      BOT_WEBHOOK_SECRET: ${BOT_WEBHOOK_SECRET}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8071:8080"
    env_file:
      - .env
    networks:
        - planner-network

networks:
    planner-network:
        external: true