ktor:
  application:
    modules:
      - ru.planner.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

postgres:
  url: "jdbc:postgresql://localhost:5439/planner"
  user: planner
  password: planner